from Crypto.Hash import SHA1

g = 0x6e65b79267d0cc573d66bfd9669b0f8995cb7f3edd52bfb69e6a0fb2f45b888170ed40a65a3a6f55914f34c3805a976661e7a3fa8a4cbb5cd3d0c080be1768c44142000fb3f436cc8a417b7c6abd4d9ce6b15b9b47b98ff7c630ad79fdcec02cc9fce12e8203d969ba1b62f289dbf1c04d355f77de2d463db4597489ffb2371d
p = 0xe01666291cebe07050c8f3c6f0365863901e803fa6ee75c44b6511266d387fc766d468c53396651edf7a4ee97ff704e3795913c401aff65e06bfcfc857aea9090aa919dee263884ca4f8936b8e40674878f3c9f1c0729a854498e3098817d1974b49d4e169c20f32e9b5dfda4989606ae9bf4d654e9a409bc592e140d088cd2b
q = 0xcab5e9b9aa5bda66528c56c064a8c449ad273005 
y = 0xbf66b0261c3739642799fbe88cf92bc9d7f7b7f6f06e4465ecd74a7c8c3e9ad2469b5dd1d6dbb586d40dc9e54b2a4e545e4b79cdb981ccb494ae1f2bff5cd8dbb53c3bb64ed0c82c43100fd7e730741be5832cbb447934479ecdf3678892dc48717b78f766c1f623f5aac6f7784cabe9f62fe643d42ea1193d48764752592370
r = 0xb93e0fe599a5013eecfdb4c6dd1f954d17ea3b52
trueFlag1 = "flag{this_is_an_example}"
trueM1 = trueFlag1.encode()
trueH1 = int(SHA1.new(trueM1).hexdigest(), 16)
trueS1 = 0x76b5e383b26ca8cad34dc6d0177a18be64f827b0 

trueFlag2 = "flag{this_is_another_example}"
trueM2 = trueFlag2.encode()
trueH2 = int(SHA1.new(trueM2).hexdigest(), 16)
trueS2 = 0x4affc4fc4cdb0736e00359b26b8010fd36fc27e3 

k = (trueH1 - trueH2) * pow(trueS1 - trueS2, -1, q) % q
x = (trueS1*k-trueH1) * pow(r,-1,q) % q

newK = 0xc431208a07dd484674c9da79c2dff66eb7b03512
fakeFlag = "This is a fake flag generated by Felicia."
fakeM = fakeFlag.encode()
fakeH = int(SHA1.new(fakeM).hexdigest(), 16)
fakeR = pow(g, newK, p) % q
fakeS = (pow(newK, -1, q)*(fakeH + x*fakeR)) % q

print(fakeR) # 685815548734516646095791724465709932518357303164
print(fakeS) # 569077031761163581620187079405767654259023701202

